name: FE Stg S3
on:
  workflow_dispatch:
  push:
    tags:
    - v.*-stg-s3

jobs:
  Run:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v1

        - name: Setup Node environment
          uses: actions/setup-node@v2
          with:
            node-version: 20

        - name: Install dependencies
          run: |
            npm cache clean --force
            npm install --legacy-peer-deps

        - name: Build project
          run: |
            CI=false npm run staging

        - name: List Build Directory
          run: ls build/

        - name: Copy files in public folder
          run: |
            mkdir deploy
            cp -r build/* deploy/

        - name: Configure AWS Credentials
          uses: aws-actions/configure-aws-credentials@v1
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ${{ secrets.AWS_REGION }}

        - name: Deploy static site to S3 bucket
          run: aws s3 sync ./deploy/ s3://${{ secrets.S3_BUCKET_STG }} --delete

        - name: Request Invalidation to AWS Cloudfront
          uses: oneyedev/aws-cloudfront-invalidation@v1
          with:
            distribution-id: ${{ secrets.STG_CLOUDFRONT_DISTRIBUTION_ID }}